### ISSUE TITLE
[BUG] Jake crashes on ddt scan "AttributeError: 'OssIndexComponent' object has no attribute 'has_known_vulnerabilities'"

### ISSUE THREAD

**Issue by angushenderson** [sonatype-nexus-community/jake#112]
**Describe the bug**
When running a jake scan an AttributeError is raised when checking for vulnerabilities (AttributeError: 'OssIndexComponent' object has no attribute 'has_known_vulnerabilities'), full stack trace is shown in screenshot below. For context, all python modules are installed via pipenv. I've tried running this command in 3 places, and this error is thrown in each of them: locally in command line, locally using pre-commit hooks, and on Gitlab ci.

**To Reproduce**
1. Enter virtual environment and run `pipenv install --dev` to install all dependencies (see Pipfile below).
2. Run `pipenv run jake ddt --clear-cache` (`--clear-cache` flag is used as per issue https://github.com/sonatype-nexus-community/jake/issues/100)
3. See error

**Expected behavior**
Normal, error free, execution of Jake OSS Index-backed scan

**Screenshots**
![image](https://user-images.githubusercontent.com/45071096/153893207-bf9aaa27-7e16-4b07-acc1-e9e7871d5548.png)

**Additional Context**
Here is the 'Pipfile':
```
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]
flake8 = "*"
pytest = "*"
coverage = "*"
pre-commit = "*"
flake8-docstrings = "*"
pep8-naming = "*"
black = "*"
moto = {extras = ["all"], version = "*"}
uvicorn = "*"
boto3 = "*"
pylint = "*"
pytest-env = "*"
diagrams = "*"
handsdown = "*"
isort = "*"
doit = "*"
factory-boy = "*"
interrogate = "*"
pytest-mock = "*"
bandit = "*"
jake = "~=1.4.4"

[packages]
fastapi = {extras = ["ujson", "requests", "orjson"], version = "*"}
mangum = "*"
watchtower = "*"
jwcrypto = "*"
sqlalchemy = "*"
mysqlclient = "*"
pycryptodome = "*"
pymysql = "*"
sqlalchemy-utils = "*"

[requires]
python_version = "3.8"
[pipenv]
allow_prereleases = true
```

Pre-commit hook in '.pre-commit-config.yaml':
```
repos:
  - repo: local
    hooks:
      - id: jake
        name: jake
        entry: pipenv run jake ddt
        language: python
        types_or: [python, pyi]
        pass_filenames: false
        # To circumvent issue stated here: https://github.com/sonatype-nexus-community/jake/issues/100
        args: [--clear-cache]
```

And the command getting run on the ci is:
`pipenv run jake ddt --clear-cache`

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.3 LTS
 - Python Version: 3.8.10
 - Version 1.4.4
